apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-svc
  name: nginx
spec:
  containers:
  - image: registry.hub.docker.com/library/nginx:latest
    name: nginx
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: regcred
