apiVersion: v1
kind: Secret
metadata:
  name: tkc01
  namespace: default
stringData:
  password: <enter-your-vCenter-password-here>
  username: administrator@vsphere.local #or change the user here
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    osInfo: photon,3,amd64
    tkg/plan: dev
  labels:
    tkg.tanzu.vmware.com/cluster-name: tkc01
  name: tkc01
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 100.86.0.0/16
    services:
      cidrBlocks:
      - 100.66.0.0/16
  topology:
    class: tkg-vsphere-default-v1.0.0
    controlPlane:
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: image-type=ova,os-name=photon
      replicas: 1
    variables:
    - name: controlPlaneCertificateRotation
      value:
        activate: true
        daysBefore: 90
    - name: auditLogging
      value:
        enabled: true
    - name: podSecurityStandard
      value:
        audit: baseline
        deactivated: false
        warn: baseline
    - name: aviAPIServerHAProvider
      value: true
    - name: vcenter
      value:
        cloneMode: fullClone
        datacenter: /vc01 #datacentername
        datastore: /vc01/datastore/vsanDatastore #datastore to place your nodes
        folder: /vc01/vm/TKG #VM folder to place your nodes
        network: /vc01/network/user-workload #portgroup to connect your workload nodes to
        resourcePool: /vc01/host/vc01cl01/Resources #resource pool to add your workload nodes to (root = /Resource)
        server: <enter-your-center-FQDN-here>
        storagePolicyID: "" #configure storage policy if applicable
        template: /vc01/vm/TKG/photon-3-kube-v1.24.10+vmware.1 #which PhotonOS kubernetes image to use (depending on TKG version, image should be available as template at this location)
        tlsThumbprint: ""
    - name: user
      value:
        sshAuthorizedKeys:
        - none
    - name: controlPlane
      value:
        machine:
          diskGiB: 40
          memoryMiB: 8192
          numCPUs: 2
    - name: worker
      value:
        count: 1
        machine:
          diskGiB: 200
          memoryMiB: 16384
          numCPUs: 2
    version: v1.24.10+vmware.1
    workers:
      machineDeployments:
      - class: tkg-worker
        metadata:
          annotations:
            run.tanzu.vmware.com/resolve-os-image: image-type=ova,os-name=photon
        name: md-0
        replicas: 4
