apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53
  namespace: cert-manager
spec:
  acme:
    email: <email-address>
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:  
    - dns01:
        route53:
          region: <aws-region-hosting-your-route53-domain>
          accessKeyID: <acceskeyID>
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: password.txt
      selector:
        dnsZones:
        - '<your-domain>'
